project:
  type: website
  output-dir: docs

website:
  title: "Emmanuel's Site"
  navbar:
    background: "#112a39"
    right:
      - about.qmd
      - icon: github
        href: https://github.com//EpicET.github.io
      

format:
  html:
    title-block-banner: img/landscape.png
    title-block-banner-color: white
    respect-user-color-scheme: true
    theme: cosmo
    css: styles.css





