project:
  type: website
  output-dir: docs

website:
  navbar:
    background: "secondary"
    left: 
      - text: "Home"
        href: index.qmd
      - text: "Blog"
        href: posts.qmd
      - about.qmd
     
    right:
      - icon: github
        menu: 
          - text: Source Code
            href: https://github.com/EpicET/EpicET.github.io
          - text: Report a Bug
            href: https://github.com/EpicET/EpicET.github.io/issues
        
      

format:
  html:
    theme:
      light: flatly
      dark: darkly
    respect-user-color-scheme: true
    css: styles.css





