project:
  type: website
  output-dir: docs

website:
  title: "Home"
  navbar:
    background: "#112a39"
    right:
      - about.qmd
      - icon: github
        href: https://github.com//EpicET.github.io
  announcement: 
    icon: info-circle
    dismissable: true
    content: "**Alert** - This website is undergoing redevelopment. Some content or features may change during this period."
    type: primary
    position: below-navbar
      

format:
  html:
    respect-user-color-scheme: true
    theme:
      light: flatly
      dark: darkly
    css: styles.css





